export const GET_LIST_ARTICLES = 'GET_LIST_ARTICLES';
export const GET_LIST_ARTICLES_ERROR = 'GET_LIST_ARTICLES_ERROR';
export const GET_DETAIL_ARTICLE = 'GET_DETAIL_ARTICLE';
export const GET_DETAIL_ARTICLE_ERROR = 'GET_DETAIL_ARTICLE_ERROR';
